import type { Metadata } from "next";
import ServerPannel from "@/app/core/components/server-pannel/server-pannel";
import NavPannel from "@/app/core/components/nav-pannel/nav-pannel";

export const metadata: Metadata = {
  title: "Createa Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-slate-900 flex  max-h-screen max-w-screen  overflow-hidden">
      <ServerPannel />
      <NavPannel />
      {children}
    </div>
  );
}
